.circleci/config.yml
Push the chart to giantswarm catalog as well
=> push to giantswarm catalog as well

CHANGELOG.md, helm/cert-manager-app/Chart.yaml, helm/cert-manager-app/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8764
=> Update to v0.13.0

CHANGELOG.md, helm/cert-manager-app/Chart.yaml, helm/cert-manager-app/values.yaml
Reverts giantswarm/cert-manager-app#11
=> Revert "Update to v0.13.0"

CHANGELOG.md, helm/cert-manager-app/Chart.yaml, helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/job.yaml, helm/cert-manager-app/templates/deployment.yaml, helm/cert-manager-app/values.yaml
Toward https://github.com/giantswarm/giantswarm/issues/8939
using `.Values.global.image.registry` take effect on all sub chart incl parent chart.
=> Using global.image.registry

helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/cm.yaml
I found a template error on configmap.
=> Fixing template error

helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/cm.yaml, helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/np.yaml, helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/service-account.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8792
=> Fix subchart namespace

helm/cert-manager-app/charts/giantswarm-cluster-issuer/values.yaml, helm/cert-manager-app/templates/rbac.yaml, helm/cert-manager-app/values.yaml
And remove namespace from values
=> Fix wrong namespace references

CHANGELOG.md, helm/cert-manager-app/templates/deployment.yaml, helm/cert-manager-app/values.yaml
towards giantswarm/giantswarm/issues/10067
* make resource requests/limits configurable via `values.yaml`.
* increase memory limit from 100Mi to 200Mi.
=> Make resources customisable

CHANGELOG.md
This has been tested on 11.2.1 on AWS - worked as expected.
=> release v1.0.8

CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/11081
=> Fix Unreleased changelog link

README.md
Adding in a section I missed regarding the API group change.
=> update upgrade docs with API group changes

CHANGELOG.md, helm/cert-manager-app/Configuration.md, helm/cert-manager-app/templates/cainjector-deployment.yaml, helm/cert-manager-app/templates/controller-deployment.yaml, helm/cert-manager-app/values.yaml
towards giantswarm/giantswarm/issues/12409
=> fix leader election namespace

CHANGELOG.md
looks like i missed this and it's causing the release workflow to fail.
=> correct changelog formatting

.circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/12935
=> Push to control plane app catalogs

.circleci/config.yml, CHANGELOG.md
This reverts commit b90febfefc1ef13acf11b4e3a3f3d779c6654134.
Towards https://github.com/giantswarm/giantswarm/issues/13129
=> Revert "Disable push to CP app-catalog (#67)"

.github/pull_request_template.md, CODEOWNERS
Adding the app squad Github team as codeowners to ensure they are pinged for a review on every PR.
=> add codeowners file

CHANGELOG.md, helm/cert-manager-app/templates/cainjector-deployment.yaml, helm/cert-manager-app/templates/controller-deployment.yaml, helm/cert-manager-app/templates/webhook-deployment.yaml
This PR:
- Updates `cert-manager` image versions to 1.0.3
No testing is required - this is just minor internal bugfixes
=> bump cert-manager to v1.0.3

CHANGELOG.md, helm/cert-manager-app/templates/cainjector-rbac.yaml, helm/cert-manager-app/templates/controller-rbac.yaml, helm/cert-manager-app/templates/crd-install/crd-rbac.yaml, helm/cert-manager-app/templates/webhook-rbac.yaml
This PR:
- Updates RBAC manifests to remove deprecated APIs
=> update deprecated rbac apis

.circleci/config.yml
update architect orb to the current latest release
=> bump architect to the latest version

helm/cert-manager-app/Chart.yaml
This updates the app icon to use our static web assets server.
=> Update app icon

CHANGELOG.md, helm/cert-manager-app/Chart.yaml, helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/rbac.yaml, helm/cert-manager-app/files/certificates.yaml, helm/cert-manager-app/files/clusterissuers.yaml, helm/cert-manager-app/files/issuers.yaml, helm/cert-manager-app/files/orders.yaml, helm/cert-manager-app/templates/controller-rbac.yaml, helm/cert-manager-app/templates/webhook-mutating-webhook.yaml, helm/cert-manager-app/templates/webhook-validating-webhook.yaml, helm/cert-manager-app/values.schema.json, helm/cert-manager-app/values.yaml
=> update to 1.1.0

CHANGELOG.md, helm/cert-manager-app/values.yaml
=> Dockerregistry

.circleci/config.yml, CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/16674#issuecomment-819438609
=> change changelog

helm/cert-manager-app/requirements.lock, helm/cert-manager-app/tests/abs/test_basic_cluster.py, helm/cert-manager-app/values.yaml
PR to update the charts requirements.lock file to match its packaged counterpart in catalog (at least digest and name should match now)
=> Update requirements.lock to match file in catalogs

CHANGELOG.md, helm/cert-manager-app/templates/cainjector-deployment.yaml, helm/cert-manager-app/templates/controller-deployment.yaml, helm/cert-manager-app/templates/webhook-deployment.yaml
Towards including cert-manager-app in sli monitoring
=> Add giantswarm.io/monitoring_basic_sli: true to deployments

.circleci/config.yml
=> push to openstack app collection

CHANGELOG.md, tests/ats/Pipfile, tests/ats/Pipfile.lock, tests/ats/test_basic_cluster.py
This PR:
- updates pytest-helm-chars to version 0.7.0
- updates test dependencies
=> Update pytest-helm-chart v0.7.0 and dependencies

CHANGELOG.md, README.md
This PR:
- Fixes some broken URLs in the README
=> Fix broken URLs

CHANGELOG.md, helm/cert-manager-app/templates/crd-install/crd-rbac.yaml
Fixes https://github.com/giantswarm/giantswarm/issues/22992.
=> crd-install/rbac: Add required capabilities.

CHANGELOG.md, helm/cert-manager-app/templates/webhook-deployment.yaml, helm/cert-manager-app/templates/webhook-pdb.yaml, helm/cert-manager-app/values.schema.json, helm/cert-manager-app/values.yaml
Closes https://github.com/giantswarm/giantswarm/issues/21133.
=> templates/webhook: Add PodDisruptionBudget.

CHANGELOG.md, helm/cert-manager-app/templates/startupapicheck-np.yaml
Closes https://github.com/giantswarm/giantswarm/issues/23342.
=> templates/startupapicheck: Add NetworkPolicy.

.circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/22753
=> Don't push to openstack and vsphere app collection

CHANGELOG.md, helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/podsecuritypolicy.yaml, helm/cert-manager-app/templates/cainjector-rbac-psp.yaml, helm/cert-manager-app/templates/crd-install/podsecuritypolicy.yaml
Even though the job is not including neither secrets nor projected volumes, they might get injected during runtime.
This PR:
- Allows more volume types in jobs' PSPs.
=> templates: Align hook PSPs to actual needs.

CHANGELOG.md, helm/cert-manager-app/templates/controller-psp.yaml
This PR:
- add missing permission `volumes: projected` to controller-psp manifest which is required for IRSA on AWS
=> Fix psp permissions

CHANGELOG.md, helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/job.yaml, helm/cert-manager-app/templates/cainjector-deployment.yaml, helm/cert-manager-app/templates/controller-deployment.yaml, helm/cert-manager-app/templates/crd-install/job.yaml, helm/cert-manager-app/templates/webhook-deployment.yaml
This PR is towards https://github.com/giantswarm/roadmap/issues/2135
=> Add: control-plane toleration to list of tolerations

.circleci/config.yml, CONTRIBUTING.md, README.md
=> Repository: Rename `master` to `main`.

.circleci/config.yml
https://gigantic.slack.com/archives/CLPMFRVU6/p1679590585037209
=> Do not push to shared-app-collection

CHANGELOG.md, helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/job.yaml, helm/cert-manager-app/templates/cainjector-deployment.yaml, helm/cert-manager-app/templates/controller-deployment.yaml, helm/cert-manager-app/templates/crd-install/job.yaml, helm/cert-manager-app/templates/webhook-deployment.yaml, helm/cert-manager-app/values.yaml
This PR updates the pod and container security policies to be compliant to PodSecurityStandard restricted profile
=> Comply to PSS restricted profile

.github/pull_request_template.md
=> GitHub: Rename `nginx-ingress-controller-app` & `hello-world-app` in pull request template.

docs/upgrading.md
=> Review and update upgrading.md

CHANGELOG.md, helm/cert-manager/values.schema.json, helm/cert-manager/values.yaml
Explicitly set `ciliumNetworkPolicy.enabled` to `false` in default values https://gigantic.slack.com/archives/C02GLN41UP2/p1690362292522879
=> Explicitly set `ciliumNetworkPolicy.enabled` to `false` in default values

CHANGELOG.md, helm/cert-manager/templates/controller-config.yaml
This PR is a follow up to #350 which adds the missing controller config ConfigMap template. Will be released as v3.2.1
=> Add missing controller config ConfigMap template

CHANGELOG.md, helm/cert-manager/Chart.lock, helm/cert-manager/values.yaml
This PR removes the control plane node toleration of the CA injector deployment. Towards https://github.com/giantswarm/giantswarm/issues/28283
=> Remove control plane node toleration of CA injector deployment.

.github/pull_request_template.md, CHANGELOG.md, helm/cert-manager/Chart.yaml, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/Chart.yaml, helm/cert-manager/charts/cert-manager-giantswarm-netpol/Chart.yaml
Move cert-manager alerts to BigMac
https://github.com/giantswarm/giantswarm/issues/27962
=> Change ownership to BigMac

CHANGELOG.md, helm/cert-manager/Chart.yaml, helm/cert-manager/values.schema.json, helm/cert-manager/values.yaml
This will allow fixing https://github.com/giantswarm/teleport-fleet/actions/runs/6953552559/job/18918867354
=> Add condition for cert-manager-giantswarm-netpol subchart

.circleci/config.yml, .github/dependabot.yml, .github/workflows/zz_generated.check_values_schema.yaml, .github/workflows/zz_generated.create_release.yaml, .github/workflows/zz_generated.create_release_pr.yaml, .github/workflows/zz_generated.gitleaks.yaml, .github/workflows/zz_generated.update_chart.yaml, CHANGELOG.md, helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/clusterrole.yaml, helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/podsecuritypolicy.yaml, helm/cert-manager-app/templates/cainjector-psp.yaml, helm/cert-manager-app/templates/cainjector-rbac-psp.yaml, helm/cert-manager-app/templates/controller-psp.yaml, helm/cert-manager-app/templates/controller-rbac-psp.yaml, helm/cert-manager-app/templates/crd-install/clusterrole.yaml, helm/cert-manager-app/templates/crd-install/podsecuritypolicy.yaml, helm/cert-manager-app/templates/webhook-psp.yaml, helm/cert-manager-app/templates/webhook-rbac-psp.yaml
This PR:
- Changes conditional for PSPs to `{{- if not .global.podSecurityStandards.enforced }}`
=> podSecurityStandards conditional

CHANGELOG.md, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/templates/clusterrole.yaml, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/templates/job.yaml, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/values.yaml
This PR:
- adds readiness check for `cert-manager-app-webhook` before attempting installation of `clusterIssuers` chart.
=> ClusterIssuers installation readiness check

CHANGELOG.md, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/templates/_helpers.tpl, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/templates/azure-dns-secret.yaml, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/values.schema.json, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/values.yaml
Towards [30243](https://github.com/giantswarm/giantswarm/issues/30243)
This PR:
- Adds conditional templating to ClusterIssuer and Secret generation in the Helm chart to support AzureDNS integration with a Service Principal.
=> Azure Cert Manager Service Principal implementation

CHANGELOG.md, helm/cert-manager/templates/cainjector-vpa.yaml, helm/cert-manager/values.schema.json, helm/cert-manager/values.yaml
Towards: [#30944](https://github.com/giantswarm/giantswarm/issues/30944)
This PR:
- adds support for Vertical Pod Autoscaler for `cainjector` deployment.
=> verticalPodAutoscaler implementation for cainjector

CHANGELOG.md, helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/templates/_helpers.tpl, helm/cert-manager/templates/_gs-helpers.tpl, helm/cert-manager/templates/cainjector-deployment.yaml, helm/cert-manager/templates/deployment.yaml, helm/cert-manager/templates/startupapicheck-job.yaml, helm/cert-manager/templates/webhook-deployment.yaml
Towards: https://github.com/giantswarm/roadmap/issues/3493
This PR:
- changes the way registry is being set in helm templates
=> Registry fix

CHANGELOG.md, helm/cert-manager/templates/cainjector-vpa.yaml, helm/cert-manager/values.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/31279
This PR:
- adds optional configuration for the VPA
=> Configurable VPA

CHANGELOG.md, helm/cert-manager/templates/controller-vpa.yaml, helm/cert-manager/values.schema.json, helm/cert-manager/values.yaml, sync/patches/values/000-values.patch, sync/patches/values/000-values.schema.patch, sync/templates/controller-vpa.yaml
Related issue: https://github.com/giantswarm/giantswarm/issues/33249
This PR:
- adds VPA support for `cert-manager-controller`
=> VPA implementation for Cert-manager controller
