giantswarm/cert-manager-app

.circleci/config.yml
CHANGELOG.md
helm/cert-manager-app/templates/deployment.yaml

Towards https://github.com/giantswarm/giantswarm/issues/6817
Additionally e2e tests are disabled for master since wrongly same default-test-catalog is used regardless of branch being built https://github.com/giantswarm/cert-manager-app/blob/master/.circleci/config.yml#L31

Remove CPU limits

---

helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/np.yaml
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/psp.yaml

It's not clear to me whether this is a change in Helm between 2.14 and 2.16 or if it only surfaced due to the default deny-all network policy in the 1.16 release, but cert-manager-giantswarm-clusterissuer is unable to communicate with the Kubernetes API as its network policy in the pre-install hook is deleted before it runs in the post-install hook. See the tiller logs in the comment below for more info.
I have a similar PR for kiam-app here https://github.com/giantswarm/kiam-app/pull/10 since it was showing similar behavior on AWS 1.16 clusters. I'm not sure if any other apps need to be updated.

Move clusterissuer NP and PSP to post-install hook

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml

Towards https://github.com/giantswarm/giantswarm/issues/8676
Used same as in upstream chart https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/Chart.yaml#L8

Configure app icon

---

helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/rbac.yaml

ClusterRoleBinding do not support namespaces in the roleref section. Installing the chart resulted in an error

Fixing invalid ClusterRoleBinding

---

helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/job.yaml

Testing with helm 3 again revealed the issue, helm 2 testing on gauss didn't complain.

Fix indenting

---

README.md
files/migrate-v090-to-v200.sh

towards https://github.com/giantswarm/giantswarm/issues/10403
This PR adds a script which can be used by customers or SEs to migrate resources to the new cert-manager API group. It is written in bash to be as portable as possible across local systems.
And yes - I am slightly disgusted with some of the JSON-parsing hoops I had to jump through :man_shrugging:

Add migration script

---

CHANGELOG.md
helm/cert-manager-app/templates/_helpers.tpl

we should only attempt to install CRDs on initial chart installation as it causes chart upgrades to fail.

don't attempt to install CRDs during upgrades

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/templates/cainjector-deployment.yaml
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/templates/webhook-deployment.yaml

towards https://github.com/giantswarm/giantswarm/issues/12549

Upgrade to 0.16.1

---

CHANGELOG.md
helm/cert-manager-app/templates/_helpers.tpl

We should always attempt to upgrade CRDs when the app is upgraded.

re-introduce pre-upgrade hook for CRDs

---

helm/cert-manager-app/charts/crd-install-cleanup/Chart.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/job.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/np.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/psp.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/rbac.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/service-account.yaml
helm/cert-manager-app/charts/crd-install-cleanup/values.yaml
helm/cert-manager-app/templates/_helpers.tpl
helm/cert-manager-app/templates/crd-configmap.yaml
helm/cert-manager-app/templates/crd-job.yaml
helm/cert-manager-app/templates/crd-np.yaml
helm/cert-manager-app/templates/crd-psp.yaml
helm/cert-manager-app/templates/crd-rbac.yaml
helm/cert-manager-app/templates/crd-serviceaccount.yaml

towards https://github.com/giantswarm/giantswarm/issues/12798
Using the current unix time is the best way I can find to make the resource names unique. Using a random string doesn't work because each time the template is called, the string is different.
In order to avoid orphaned resources being left behind, I've also added a label which can be used to select all crd hook resources - these are used by a new sub-chart which runs at the post-install and post-upgrade stages which deletes all resources with this label.
The subchart's RBAC rules are as restrictive as possible - the pod can only list the resource types it needs, and it can only delete the named resources.

Unique names for hook resources

---

CHANGELOG.md
helm/cert-manager-app/files/crds.yaml

Towards giantswarm/giantswarm#12935
Missing dash prevented `orders.acme.cert-manager.io` CR from being requested/created with the following error
```
Error from server: conversion webhook for acme.cert-manager.io/v1alpha2, Kind=Order failed: Post https://cert-manager-webhook.giantswarm.svc:443/convert?timeout=30s: x509: certificate signed 
by unknown authority  
```

Fix secret name for orders.acme.cert-manager.io

---

helm/cert-manager-app/templates/crd-rbac.yaml

Fixes
```
Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "clusterissuers.cert-manager.io", Namespace: ""
for: "/data/crds.yaml": customresourcedefinitions.apiextensions.k8s.io "clusterissuers.cert-manager.io" is forbidden: User "system:serviceaccount:kube-system:cert-manager-crd-install-1599220793" cannot patch resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

Patch CRD upgrade

---

CHANGELOG.md
helm/cert-manager-app/charts/giantswarm-cluster-issuer/values.yaml

towards giantswarm/giantswarm/issues/13119
drop the pod resource limits to stop it being killed when running on CPs

drop resource limit for clusterissuer subchart job

---

CHANGELOG.md
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/rbac.yaml

```
for: "/data/clusterissuer": clusterissuers.cert-manager.io "selfsigned-giantswarm" is forbidden: User "system:serviceaccount:kube-system:cert-manager-giantswarm-clusterissuer" cannot patch resource "clusterissuers" in API group "cert-manager.io" at the cluster scope
```

Update clusterissuer subchart rbac

---

.circleci/config.yml
CHANGELOG.md

This is a temporary precaution until I fix issues when upgrading cert-manager-app on CPs.

Disable push to CP app-catalog

---

README.md

To make it clear which software this chart installs, this PR adds a link to the upstream website.

Add link to upstream cert-manager to README

---

CHANGELOG.md
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/values.yaml

Configure cert manager to be able to use Route53 for DNS01 challenages

Add optional Kiam annotation for Route53

---

CHANGELOG.md
helm/cert-manager-app/charts/crd-install-cleanup/templates/job.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/np.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/psp.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/rbac.yaml
helm/cert-manager-app/charts/crd-install-cleanup/templates/service-account.yaml
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/cm.yaml
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/job.yaml
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/np.yaml
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/psp.yaml
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/rbac.yaml
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/service-account.yaml
helm/cert-manager-app/templates/_helpers.tpl

Towards https://github.com/giantswarm/giantswarm/issues/13403
Recommended solution for `already exists` error in [helm docs](https://v2.helm.sh/docs/charts_hooks/#automatically-delete-hook-from-previous-release).

Clean up resources after hooks are finished

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/templates/cainjector-deployment.yaml
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/templates/webhook-deployment.yaml
helm/cert-manager-app/values.yaml

While handling an incident https://gigantic.slack.com/archives/C03CPNRTS/p1604067749119200 I've noticed that cert-manager-app v2.3.1 based helm release, that got installed on asgard CP, has wrong cert-manager app version metadata.
It was missed in https://github.com/giantswarm/cert-manager-app/pull/86 to update Chart.yaml metadata about app version used.
This PR fixes the issue.
This PR:

Update Chart.yaml to 1.0.3

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/values.schema.json

Towards https://github.com/giantswarm/roadmap/issues/136
This PR adds `values.schema.json` generated from the current values.yaml using https://github.com/karuppiah7890/helm-schema-gen
It is a good starting point and can be further refined by those that know more about the specifics of the values. (For example if we know that `provider` must be aws|azure|kvm, we can actually enforce that as well using the 'enum' property: https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values)
Here's also some more general info: https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/
I want but couldn't validated this generated schema against the app. Wanted to try check at least in `gorilla` and `asgard` 
Got these errors in `gorilla`
```
➜ …
```

Add values.schema.json to cert manager

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/values.yaml

This PR:
- updates cert-manager to 1.0.4
This is a patch version which includes bug fixes only - the full set of tests aren't required.

update cert-manager to v1.0.4

---

files/migrate-v090-to-v200.sh

this pr corrects a daft mistake in the migration script which would cause it not to run

correct resource name in migration script

---

.circleci/config.yml
CHANGELOG.md
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/job.yaml
helm/cert-manager-app/templates/cainjector-deployment.yaml
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/templates/crd-install/crd-job.yaml
helm/cert-manager-app/templates/webhook-deployment.yaml
integration/config/kind-config
integration/config/setup.sh

Towards https://github.com/giantswarm/giantswarm/issues/14281
This PR:
- schedules crd-install job on k8s master nodes.

allow CRD install Job to run on masters

---

CHANGELOG.md
helm/cert-manager-app/charts/giantswarm-cluster-issuer/misc/clusterissuers.yaml

This PR:
- bumps the api group of the clusterissuer subchart to `v1`
- Testing isn't required - this API version has been available in this chart for a while now. This is just housekeeping.

update api group for clusterissuer subchart resources

---

CHANGELOG.md
helm/cert-manager-app/charts/giantswarm-cluster-issuer/templates/job.yaml
helm/cert-manager-app/charts/giantswarm-cluster-issuer/values.yaml

This PR:
- makes clusterissuer job backofflimit configurable
Testing isn't needed for this PR.

make clusterissuer job backofflimit configurable

---

CHANGELOG.md
helm/cert-manager-app/templates/crd-install/crd-job.yaml
helm/cert-manager-app/values.schema.json
helm/cert-manager-app/values.yaml

This PR:
- makes the backofflimit for the crd-install job configurable.
- bumps the backofflimit to 10 (up from the default of 6).
no testing required (aside from rendering the chart locally).

make the crd job backofflimit configurable

---

.abs/main.yaml

Updates the catalog domain to giantswarm.github.io instead of giantswarm.github.com. Towards giantswarm/giantswarm#15898

Update catalog domain to github.io

---

.abs/main.yaml
.github/workflows/check_values_schema.yaml
CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/templates/controller-rbac.yaml
helm/cert-manager-app/values.schema.json
helm/cert-manager-app/values.yaml

This PR updates the used cert-manager image to 1.2.0.
This chart now requires kubernetes >= 1.16.0 because it switches rbac rules from `extensions` to `networking.k8s.io` for ingresses.
I tested
- on AWS: upgrading + issuing a certificate using ingress
- on Azure: Installing + issueing a certificate using ingress.

Upgrade controller image to v1.2.0

---

CHANGELOG.md
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/values.schema.json
helm/cert-manager-app/values.yaml

This PR:
- sets the authoritative nameserver for the dns01 solver

set the DNS server from the installation config when using dns01 solver

---

.circleci/config.yml
CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/ci/default-values.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/cm.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/values.yaml
helm/cert-manager-app/ci/default-values.yaml
helm/cert-manager-app/templates/cloudflare-secret.yaml
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/values.schema.json
helm/cert-manager-app/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/18189
This PR:
- migrates values structure to better fit with giantswarm/config.
- allows successful configuration of the acme solver type.
This change allows the chart to continue to be used in WCs because the defaulting remains the same (http01). The only time this will affect customers is if they're using dns01 challenge - this needs to be covered in the release notes.
The main reason for this PR is because the acme solver cannot be configured due to variable scoping issues (see the issue linked above)

migrate app values to config repo layout

---

CHANGELOG.md
helm/cert-manager-app/templates/controller-service.yaml

This PR adds labels and annotations required for metric scraping. 
Towards https://github.com/giantswarm/giantswarm/issues/17817

Add metrics scraping metadata to controller service

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/files/certificaterequests.yaml
helm/cert-manager-app/files/certificates.yaml
helm/cert-manager-app/files/challenges.yaml
helm/cert-manager-app/files/clusterissuers.yaml
helm/cert-manager-app/files/issuers.yaml
helm/cert-manager-app/files/orders.yaml
helm/cert-manager-app/templates/_helpers.tpl
helm/cert-manager-app/templates/controller-rbac.yaml
helm/cert-manager-app/templates/startupapicheck-job.yaml
helm/cert-manager-app/templates/startupapicheck-rbac.yaml
helm/cert-manager-app/templates/startupapicheck-serviceaccount.yaml
helm/cert-manager-app/templates/webhook-deployment.yaml
helm/cert-manager-app/templates/webhook-mutating-webhook.yaml
helm/cert-manager-app/templates/webhook-service.yaml
helm/cert-manager-app/templates/webhook-validating-webhook.yaml
helm/cert-manager-app/values.schema.json
helm/cert-manager-app/values.yaml

This PR:
Upgrades the chart to use cert-manager 1.5.3. This is the first version to support Kubernetes 1.22.
It also adds a helm post-install hook which deploys a job to check cert-manager readiness.

Upgrade to 1.5.3

---

helm/cert-manager-app/templates/_helpers.tpl

I saw this in the crd-install job
```
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "certificaterequests.cert-manager.io" is invalid: metadata.labels: Invalid value: "cert-manager-app-2.10.0-33763c8bf729330e5d61cc85a7d2599702cda183": must be no more than 63 characters
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "certificates.cert-manager.io" is invalid: metadata.labels: Invalid value: "cert-manager-app-2.10.0-33763c8bf729330e5d61cc85a7d2599702cda183": must be no more than 63 characters
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "challenges.acme.cert-manager.io" is invalid: metadata.labels: Invalid value: "cert-manager-app-2.10.0-33763c8bf729330e5d61cc85a7d2599702cda183": must be no more than 63 …
```

change helm.sh/chart label in crds to be shorter

---

CHANGELOG.md
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/cm.yaml

Adds special label to default installed issuers in preparation for changes in metrics/alerting together with https://github.com/giantswarm/cert-exporter/pull/176

Add giantswarm-managed issuer labels

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/templates/startupapicheck-psp-clusterrole.yaml
helm/cert-manager-app/templates/startupapicheck-psp-clusterrolebinding.yaml
helm/cert-manager-app/templates/startupapicheck-psp.yaml
helm/cert-manager-app/templates/startupapicheck-rbac.yaml
helm/cert-manager-app/templates/startupapicheck-serviceaccount.yaml
helm/cert-manager-app/values.yaml

Towards giantswarm/giantswarm#19074
This PR:
- fixes installation issues
- tested on `gauss` with `16.0.0-calvix` and `15.3.0-njuettner`

fix psp for startupapicheck from upstream

---

.ats/main.yaml
.circleci/config.yml
.gitignore
tests/ats/Pipfile.lock
tests/ats/test_basic_cluster.py

This PR:
Updates CI dependencies architect-orb to 4.8.1 (using app-test-suite 0.2.2) which enables us to execute upgrade tests.

Bump ats to enable upgrade tests

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/files/certificaterequests.yaml
helm/cert-manager-app/files/certificates.yaml
helm/cert-manager-app/files/challenges.yaml
helm/cert-manager-app/files/clusterissuers.yaml
helm/cert-manager-app/files/issuers.yaml
helm/cert-manager-app/files/orders.yaml
helm/cert-manager-app/values.yaml

Towards https://github.com/giantswarm/roadmap/issues/528
This PR:
- Updates the used cert-manager version to 1.6.1

Upstream v1.6.1

---

CHANGELOG.md
helm/cert-manager-app/templates/controller-deployment.yaml

This PR: (Towards https://github.com/giantswarm/giantswarm/issues/20279)
- Changes the deployment to use retagged container image for acme solver
- lets encrypt certificate could be obtained in test on aws cluster

Use retagged container image for acme solver

---

CHANGELOG.md
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/values.yaml
helm/cert-manager-app/templates/crd-install/crd-job.yaml

This PR
Pins the used kubectl container image version from `latest` to `1.23.3` to prevent a situation when docker.io is used as registry where `latest` is very old

Use 1.23.3 kubectl container in crd install job

---

CHANGELOG.md
helm/cert-manager-app/templates/_helpers.tpl

This PR changes the default labels to include the `application.giantswarm.io/team` label with value from the Chart.yaml annotation with the same name. 
Towards https://github.com/giantswarm/giantswarm/issues/20482

add team to default labels

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/values.yaml
helm/cert-manager-app/templates/crd-install/crd-job.yaml
helm/cert-manager-app/values.yaml

This PR:
- Updates the cert-manager versions to [1.7.3](https://github.com/cert-manager/cert-manager/releases/tag/v1.7.3)
- Updates the kubectl version to 1.24.2

Upgrade cert-manager to 1.7.3

---

CHANGELOG.md
helm/cert-manager-app/templates/crd-install/crd-job.yaml

This PR:
- adds execution of `cmctl upgrade migrate-api-version` to update stored apiversions on the target cluster. This is sometimes required because etcd/api stores CRs in a specific apiversion and cert-manager 1.7 has removed support for alpha and beta version of its CRDs

Run cmctl upgrade migrate-api-version in CRD install job

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/files/certificaterequests.yaml
helm/cert-manager-app/files/certificates.yaml
helm/cert-manager-app/files/challenges.yaml
helm/cert-manager-app/files/clusterissuers.yaml
helm/cert-manager-app/files/issuers.yaml
helm/cert-manager-app/templates/cainjector-rbac.yaml
helm/cert-manager-app/templates/cainjector-serviceaccount.yaml
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/templates/controller-rbac.yaml
helm/cert-manager-app/templates/controller-serviceaccount.yaml
helm/cert-manager-app/templates/startupapicheck-serviceaccount.yaml
helm/cert-manager-app/templates/webhook-serviceaccount.yaml
helm/cert-manager-app/values.schema.json
helm/cert-manager-app/values.yaml

This PR:
- updates controller components to v1.8.2
- aligns the rbac file to upstream for better comparison

Upgrade to cert-manager v1.8.2

---

CHANGELOG.md
helm/cert-manager-app/templates/cainjector-deployment.yaml
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/templates/webhook-deployment.yaml
helm/cert-manager-app/values.schema.json
helm/cert-manager-app/values.yaml

This PR:
- adds support for running behind a proxy
- support `proxy` values
- support `cluster.proxy` values (managed/injected via `cluster-apps-operator`)
- custom `proxy` values take precedence over `cluster.proxy` variables

support behind proxy server

---

.circleci/config.yml

Tested via temporary tag: https://app.circleci.com/pipelines/github/giantswarm/cert-manager-app/1279/workflows/cb8af0e6-5952-42d6-8fad-3811ea1a2d7c
This fixes `CATALOGBOT_SSH_KEY_PRIVATE_BASE64 env variable must not be empty`.

Add CircleCI context to fix build of tags

---

CHANGELOG.md
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/_helpers.tpl
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/clusterrole.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/clusterrolebinding.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/configmap.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/job.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/networkpolicy.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/podsecuritypolicy.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/serviceaccount.yaml

Towards https://github.com/giantswarm/giantswarm/issues/27170
This PR changes installation of the `giantswarm-selfsigned` ClusterIssuer regardless of `global.giantSwarmClusterIssuer.install` value. It is required as a default component for Giant Swarm cluster installations.
Regarding cert-manager-app chart installations using the cert-manager controller flag `--namespace`: Specifying this flag makes the controller ignore ClusterIssuers.
```
--namespace string                                    If set, this limits the scope of cert-manager to a single namespace and ClusterIssuers are disabled. If not specified, all namespaces will be watched
```

Always install giantswarm-selfsigned ClusterIssuer

---

.ats/main.yaml
.circleci/config.yml
CHANGELOG.md
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/clusterrole.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/podsecuritypolicy.yaml
helm/cert-manager-app/templates/cainjector-psp.yaml
helm/cert-manager-app/templates/cainjector-rbac-psp.yaml
helm/cert-manager-app/templates/controller-psp.yaml
helm/cert-manager-app/templates/controller-rbac-psp.yaml
helm/cert-manager-app/templates/crd-install/clusterrole.yaml
helm/cert-manager-app/templates/crd-install/podsecuritypolicy.yaml
helm/cert-manager-app/templates/startupapicheck-psp-clusterrole.yaml
helm/cert-manager-app/templates/startupapicheck-psp.yaml
helm/cert-manager-app/templates/webhook-psp.yaml
helm/cert-manager-app/templates/webhook-rbac-psp.yaml
tests/ats/Pipfile
tests/ats/Pipfile.lock
tests/ats/test_basic_cluster.py

This PR prevents installation of PodSecurityPolicies on clusters running kubernetes 1.25 and above.
It also updates some testing depencencies.

Prevent installation of PodSecurityPolicies on k8s 1.25

---

CHANGELOG.md
helm/cert-manager-app/Chart.yaml
helm/cert-manager-app/charts/cert-manager-giantswarm-clusterissuer/templates/job.yaml
helm/cert-manager-app/files/certificaterequests.yaml
helm/cert-manager-app/files/certificates.yaml
helm/cert-manager-app/files/challenges.yaml
helm/cert-manager-app/files/clusterissuers.yaml
helm/cert-manager-app/files/issuers.yaml
helm/cert-manager-app/files/orders.yaml
helm/cert-manager-app/templates/cainjector-deployment.yaml
helm/cert-manager-app/templates/cainjector-rbac.yaml
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/templates/crd-install/job.yaml
helm/cert-manager-app/templates/webhook-deployment.yaml
helm/cert-manager-app/values.yaml

This PR:
- Updates container images used to upstream version 1.12.1
- Update security contexts (#324)

Update container image version to 1.12.1

---

CHANGELOG.md
helm/cert-manager-app/templates/crd-install/podsecuritypolicy.yaml

PodSecurityPolicy: Set `allowedProfileNames`.

---

CHANGELOG.md
helm/cert-manager-app/files/certificaterequests.yaml
helm/cert-manager-app/files/certificates.yaml
helm/cert-manager-app/files/challenges.yaml
helm/cert-manager-app/files/clusterissuers.yaml
helm/cert-manager-app/files/issuers.yaml
helm/cert-manager-app/files/orders.yaml

This PR adds helm annotations to CRDs. This change is done in preparation for a future major release of the chart.

Add helm adoption annotations to CRDs

---

CHANGELOG.md
helm/cert-manager-app/templates/cainjector-deployment.yaml
helm/cert-manager-app/templates/controller-deployment.yaml
helm/cert-manager-app/values.schema.json
helm/cert-manager-app/values.yaml

Towards https://github.com/giantswarm/vodafone/issues/617
This PR:
- Add `cluster-autoscaler safe-to-evict` annotation to `controller` and `cainjector`

Add `cluster-autoscaler safe-to-evict` annotation to `controller` and `cainjector`

---

CHANGELOG.md
helm/cert-manager/values.yaml
tests/ats/test_basic_cluster.py

This PR adds `fullnameOverride: 'cert-manager-app'` to default values.
This will make sure Deployment names will be 
```
cert-manager-app
cert-manager-app-cainjector
cert-manager-app-webhook
```

Make Deployment names predictable

---

CHANGELOG.md
helm/cert-manager/templates/cainjector-deployment.yaml
helm/cert-manager/templates/deployment.yaml
helm/cert-manager/templates/rbac.yaml
helm/cert-manager/templates/startupapicheck-job.yaml
helm/cert-manager/templates/webhook-deployment.yaml
helm/cert-manager/values.yaml
vendir.lock.yml

This PR syncs the chart template code with upstream
- Make `spec.enableServiceLinks` field configurable for controller, cainjector and webhook Deployments and startupapicheck Job. ([#350](https://github.com/giantswarm/cert-manager-app/pull/350))
- Update chart from upstream. Relevant upstream PRs: [#6241](https://github.com/cert-manager/cert-manager/pull/6241), [#6156](https://github.com/cert-manager/cert-manager/pull/6156), [#6292](https://github.com/cert-manager/cert-manager/pull/6292), [#5337](https://github.com/cert-manager/cert-manager/pull/5337). ([#350](https://github.com/giantswarm/cert-manager-app/pull/350))

Configurable serviceLinks + Update from upstream

---

CHANGELOG.md
helm/cert-manager/templates/cainjector-networkpolicy.yaml
helm/cert-manager/templates/networkpolicy.yaml

This PR adds two new NetworkPolicies for controller and cainjector. Its pods require egress and api server access.

Add NetworkPolicies for controller and cainjector pods

---

CHANGELOG.md
helm/cert-manager/values.yaml

This PR:
- changes the monitoring setup to use a servicemonitor instead of service annotations

Enable ServiceMonitor by default

---

.github/workflows/zz_generated.create_release_pr.yaml
CHANGELOG.md
helm/cert-manager/Chart.yaml

This PR:
- Move cert-manager ownership to team BigMac. ([#349](https://github.com/giantswarm/cert-manager-app/pull/349))
- Add default cpu and memory limits to controller, cainjector and webhook deployments. ([#367](https://github.com/giantswarm/cert-manager-app/pull/367))
- Changes the Pod Disruption Budget (PDB) to percentage-based to allow for more flexible and resilient deployments, following cloud-native best practices. ([#372](https://github.com/giantswarm/cert-manager-app/pull/372))

Release v3.4.1

---

CHANGELOG.md
helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/templates/_helpers.tpl
helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/templates/provider-route53-secret.yaml
helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/values.schema.json
helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/values.yaml

Towards https://github.com/giantswarm/roadmap/issues/2698
In our EKS setup we set IAM role to the SA so we don't need AWS credentials.
Setting hostedZoneID allows more strict permissions for the role.

Allow setting hostedZoneID and make AWS credentials optional for route53 DNS01 challenge

---

CHANGELOG.md
helm/cert-manager/values.yaml

This PR:
- disables the `startup-api-check` job that waits for the webhookendpoints to become available (`ClusterIssuers job` will make sure `cert-manager` stuff is working, from now on)

disable startupapicheck job

---

CHANGELOG.md
helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/templates/_helpers.tpl
helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/values.schema.json
helm/cert-manager/charts/cert-manager-giantswarm-clusterissuer/values.yaml

Relevant [issue](https://github.com/giantswarm/roadmap/issues/3198)
This PR:
- adds support for `AzureDNS` on `ClusterIssuer` chart so it can be used as `dns01 challenge solver`

azure-dns01 option on clusterissuer chart

---

CHANGELOG.md
helm/cert-manager/Chart.yaml
helm/cert-manager/values.yaml

This PR:
- changes the cert-manager appVersion to v1.14.2(latest)
- CAPZ
- CAPA

bump to 1.14.2

---

CHANGELOG.md
helm/cert-manager/templates/crds.yaml

This PR:
- adds annotation `helm.sh/resource-policy: keep` on CRDs to prevent them from being pruned in an unexpected rollback event.

crd annotation

---

CHANGELOG.md
helm/cert-manager/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/30944
This PR:
- Enables VPA by default

Enable VPA by default

---

CHANGELOG.md
helm/cert-manager/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/31165
This PR:
- Improves container security by setting `runAsGroup` and `runAsUser` greater than zero (non-root) for all deployments.
- Fixes [require-non-root-group](https://kyverno.io/policies/other/require-non-root-groups/require-non-root-groups/) policy.

Set `runAsGroup` and `runAsUser` greater than zero

---

CHANGELOG.md
helm/cert-manager/templates/deployment.yaml

This PR:
Removes quotes from acme-http01-solver-image argument. The quotes are used when looking up the image which causes an error.

Fix acme-http01-solver-image argument

---

.circleci/config.yml
CHANGELOG.md

Towards https://github.com/giantswarm/giantswarm/issues/31374
This PR:
- Bump architect-orb@5.3.1 to fix CVE-2024-24790.

Bump architect-orb@5.3.1

---

CHANGELOG.md
helm/cert-manager/charts/cert-manager-giantswarm-ciliumnetworkpolicies/templates/_gs-helpers.tpl
helm/cert-manager/charts/cert-manager-giantswarm-netpol/templates/_gs-helpers.tpl
helm/cert-manager/templates/_gs-helpers.tpl

Towards https://github.com/giantswarm/giantswarm/issues/31095
This PR:
- removes the legacy in-house slo framework as it was replaced by sloth a long time ago and is now deprecated.
- The new slo is waiting for reviews https://github.com/giantswarm/sloth-rules/pull/238

remove legacy in-house slo generation framework

---

helm/cert-manager/templates/rbac.yaml
helm/cert-manager/values.schema.json
helm/cert-manager/values.yaml

This PR:
- adds the option to configure additional `approveSignerNames`

Additional `approveSignerNames` fix
